// EasingTypes.ts
export const EasingType = cc.Enum({
    LINEAR: 0,
    SINE_IN: 1,
    SINE_OUT: 2,
    SINE_IN_OUT: 3,
    QUAD_IN: 4,
    QUAD_OUT: 5,
    QUAD_IN_OUT: 6,
    CUBIC_IN: 7,
    CUBIC_OUT: 8,
    CUBIC_IN_OUT: 9,
    QUART_IN: 10,
    QUART_OUT: 11,
    QUART_IN_OUT: 12,
    QUINT_IN: 13,
    QUINT_OUT: 14,
    QUINT_IN_OUT: 15,
    EXPO_IN: 16,
    EXPO_OUT: 17,
    EXPO_IN_OUT: 18,
    CIRC_IN: 19,
    CIRC_OUT: 20,
    CIRC_IN_OUT: 21,
    BACK_IN: 22,
    BACK_OUT: 23,
    BACK_IN_OUT: 24,
    BOUNCE_IN: 25,
    BOUNCE_OUT: 26,
    BOUNCE_IN_OUT: 27,
    ELASTIC_IN: 28,
    ELASTIC_OUT: 29,
    ELASTIC_IN_OUT: 30
})

// 映射到 Cocos Creator 的 easing 字符串
export const EasingTypeMap = {
    [EasingType.LINEAR]: "linear",
    [EasingType.SINE_IN]: "sineIn",
    [EasingType.SINE_OUT]: "sineOut",
    [EasingType.SINE_IN_OUT]: "sineInOut",
    [EasingType.QUAD_IN]: "quadIn",
    [EasingType.QUAD_OUT]: "quadOut",
    [EasingType.QUAD_IN_OUT]: "quadInOut",
    [EasingType.CUBIC_IN]: "cubicIn",
    [EasingType.CUBIC_OUT]: "cubicOut",
    [EasingType.CUBIC_IN_OUT]: "cubicInOut",
    [EasingType.QUART_IN]: "quartIn",
    [EasingType.QUART_OUT]: "quartOut",
    [EasingType.QUART_IN_OUT]: "quartInOut",
    [EasingType.QUINT_IN]: "quintIn",
    [EasingType.QUINT_OUT]: "quintOut",
    [EasingType.QUINT_IN_OUT]: "quintInOut",
    [EasingType.EXPO_IN]: "expoIn",
    [EasingType.EXPO_OUT]: "expoOut",
    [EasingType.EXPO_IN_OUT]: "expoInOut",
    [EasingType.CIRC_IN]: "circIn",
    [EasingType.CIRC_OUT]: "circOut",
    [EasingType.CIRC_IN_OUT]: "circInOut",
    [EasingType.BACK_IN]: "backIn",
    [EasingType.BACK_OUT]: "backOut",
    [EasingType.BACK_IN_OUT]: "backInOut",
    [EasingType.BOUNCE_IN]: "bounceIn",
    [EasingType.BOUNCE_OUT]: "bounceOut",
    [EasingType.BOUNCE_IN_OUT]: "bounceInOut",
    [EasingType.ELASTIC_IN]: "elasticIn",
    [EasingType.ELASTIC_OUT]: "elasticOut",
    [EasingType.ELASTIC_IN_OUT]: "elasticInOut"
};

// 获取显示名称（用于工具提示等）
export const EasingDisplayNames = {
    [EasingType.LINEAR]: "Linear 线性",
    [EasingType.SINE_IN]: "Sine In 正弦缓入",
    [EasingType.SINE_OUT]: "Sine Out 正弦缓出",
    [EasingType.SINE_IN_OUT]: "Sine InOut 正弦缓入缓出",
    [EasingType.QUAD_IN]: "Quad In 二次缓入",
    [EasingType.QUAD_OUT]: "Quad Out 二次缓出",
    [EasingType.QUAD_IN_OUT]: "Quad InOut 二次缓入缓出",
    [EasingType.CUBIC_IN]: "Cubic In 三次缓入",
    [EasingType.CUBIC_OUT]: "Cubic Out 三次缓出",
    [EasingType.CUBIC_IN_OUT]: "Cubic InOut 三次缓入缓出",
    [EasingType.QUART_IN]: "Quart In 四次缓入",
    [EasingType.QUART_OUT]: "Quart Out 四次缓出",
    [EasingType.QUART_IN_OUT]: "Quart InOut 四次缓入缓出",
    [EasingType.QUINT_IN]: "Quint In 五次缓入",
    [EasingType.QUINT_OUT]: "Quint Out 五次缓出",
    [EasingType.QUINT_IN_OUT]: "Quint InOut 五次缓入缓出",
    [EasingType.EXPO_IN]: "Expo In 指数缓入",
    [EasingType.EXPO_OUT]: "Expo Out 指数缓出",
    [EasingType.EXPO_IN_OUT]: "Expo InOut 指数缓入缓出",
    [EasingType.CIRC_IN]: "Circ In 圆形缓入",
    [EasingType.CIRC_OUT]: "Circ Out 圆形缓出",
    [EasingType.CIRC_IN_OUT]: "Circ InOut 圆形缓入缓出",
    [EasingType.BACK_IN]: "Back In 回弹缓入",
    [EasingType.BACK_OUT]: "Back Out 回弹缓出",
    [EasingType.BACK_IN_OUT]: "Back InOut 回弹缓入缓出",
    [EasingType.BOUNCE_IN]: "Bounce In 弹跳缓入",
    [EasingType.BOUNCE_OUT]: "Bounce Out 弹跳缓出",
    [EasingType.BOUNCE_IN_OUT]: "Bounce InOut 弹跳缓入缓出",
    [EasingType.ELASTIC_IN]: "Elastic In 弹性缓入",
    [EasingType.ELASTIC_OUT]: "Elastic Out 弹性缓出",
    [EasingType.ELASTIC_IN_OUT]: "Elastic InOut 弹性缓入缓出"
};